### ISSUE TITLE
fix bug with camembert models

### ISSUE THREAD

**Issue by Sunalwing** [Lyon-NLP/mtebscripts#3]
This bug affects the following sentence_transformer models :
- "camembert/camembert-base"
- "camembert/camembert-large"
- "dangvantuan/sentence-camembert-large"
It may be due to a lack of compatibilty with the SentenceTransformer module, or with memory problems

**Comment by Sunalwing** [comment]
This bug affects the following sentence_transformer models :
- "camembert/camembert-base"
- "camembert/camembert-large"
- "dangvantuan/sentence-camembert-large"
It may be due to a lack of compatibilty with the SentenceTransformer module, or with memory problems

**Comment by imenelydiaker** [comment]
Seems to be a nvidia driver + torch-cuda version realted error. @wissam-sib proposes to run the script in a container with corresponding driver and package versions.
